### ISSUE TITLE
[REFACTOR] signin, signup 짜잘 수정

### ISSUE THREAD

**Issue by sinryuji** [peer-42seoul/Peer-Backend#180]
### Description
API 명세에 따라 변경된 사항들 수정합니다.

### To-Do
- [x] signin Http Method 변경
- [x] 소셜 로그인 회원 가입 시 에러 상황 추가
- [x] User 닉네임, 네임 길이 수정
