### ISSUE TITLE
[FIX] 모집글 및 팀 지역 정책 변경 내용에 따라 수정 필요

### ISSUE THREAD

**Issue by weejihye** [peer-42seoul/Peer-Backend#207]
### Description
팀과 모집글의 지역 형태가 달라서 통일화 필요
지역을 2개 스트링 배열로 보냄.

### To-Do
Recruit
- [ ] entity 수정 - String region을 List<String> region으로 수정
- [ ] dto 수정 - 동일
- [ ] service 수정 -  지역 추가시 배열 추가로 수정
Team쪽은 junssong님이 수정
