### ISSUE TITLE
[REFACTOR] apply file module in edit profile API

### ISSUE THREAD

**Issue by juhyeonlee134** [peer-42seoul/Peer-Backend#231]
### Description
- profile 정보를 수정하는 API에 파일 모듈을 적용합니다.

### To-Do
- [x] apply file module
- [x] refactor test code
- [x] fix yml file
