### ISSUE TITLE
[HOTFIX] 비밀번호 변경 관련 API

### ISSUE THREAD

**Issue by juhyeonlee134** [peer-42seoul/Peer-Backend#278]
### Description
비밀번호 변경과 관련된 API에서 문제가 생겨 다음과 같은 수정 작업을 진행합니다.
- 비밀번호 변경 API의 error code를 API 문서에 맞도록 수정합니다.
- 오류 메시지에 ' . '가 두개 있는 것을 수정합니다.
- DTO에 valid를 비밀번호 정책에 맞도록 추가합니다.

### To-Do
- [ ] error code 수정
- [ ] 오류 메시지 수정
- [ ] DTO valid 추가
