### ISSUE TITLE
[FEATURE] 쇼케이스 view페이지

### ISSUE THREAD

**Issue by weejihye** [peer-42seoul/Peer-Backend#443]
### Description
- showcase 리스트 조회
- showcase 좋아요, 관심 기능
### To-Do
- [ ] [GET /showcase/](https://github.com/orgs/peer-42seoul/projects/35?pane=issue&itemId=46277012)
- [ ] [POST /showcase/like](https://github.com/orgs/peer-42seoul/projects/35?pane=issue&itemId=46277957)
- [ ] [POST /showcase/favorite](https://github.com/orgs/peer-42seoul/projects/35?pane=issue&itemId=46278133)
