### ISSUE TITLE
[REFACTOR] 사용자 활동 추적 리팩토링

### ISSUE THREAD

**Issue by sinryuji** [peer-42seoul/Peer-Backend#477]
### Description
기존에 Enum 클래스를 통해 사용자의 활동을 정의하고 추적을 하던 부분을 DB를 이용하도록 리팩토링 합니다.

### To-Do
- [x] 사용자 활동 DB 설계
- [x] 사용자 활동 엔티티 구성
- [x] 기존 사용자 활동 추적 파트 리팩토링
