### ISSUE TITLE
[FEATURE] 사용자 추적 추가 개발

### ISSUE THREAD

**Issue by sinryuji** [peer-42seoul/Peer-Backend#554]
### Description
사용자 추적 파트에서 기능이 개발되지 않아 미뤘던 부분들을 개발합니다.

### To-Do
- [x] 사용자 영구밴 추적
- [x] 사용자 신고 누계 추적
- [x] 블랙리스트 석방 추적
