### ISSUE TITLE
[FEAT] alarm-refactoring-new-apis

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/Peer-Backend#565]
### Description
- 기존 @wochae 님의 작업을 승계받아, 내용들을 설계에 기반하여 안되어 있는 부분을 개선한다. 
- NestJS를 기반으로 생성될 서버작업도 진행 해야 한다. 

### To-Do
- [ ] 기존 작업 파악
- [ ] admin 작업들 중 @sinryuji 님이 작업하신 내용 파악하여, 계획대로 사용 가능한 서비스 제작 
- [ ] 기존 작업 중 추가로 필요하거나 수정할 작업들 전체 리스트업  & 작업 개시 
- [ ] 알람 테스팅
- [ ] NestJS 작업 리스팅 및 작업 마무리 -> PWA 연락 정상 여부 테스팅
- [ ] 마무리

**Comment by Paul2021-R** [comment]
# 인수인계 내용

## 컨트롤러

### NoticeController :
public ResponseEntity<Object> saveAlarmAdmin(@RequestBody AlarmDto dto)
public ResponseEntity<Object> getAlarm(@RequestParam(value = "type") String type)
public ResponseEntity<Object> saveAlarm(@RequestBody AlarmDto dto)
public ResponseEntity<Object> getAlarmGeneral(Authentication authentication)
public ResponseEntity<Object> deleteAllAlarm(@RequestParam(value = "type") String type)
public ResponseEntity<Object> deleteAlarm(@RequestParam Long id)

## 서비스 

### AlarmService :
public Alarm saveAlarm(AlarmDto data);
public AlarmTarget saveAlarmTarget(Alarm dto);
public AlarmTarget alarmTargetFromDto(AlarmTargetDto dto);public Alarm alarmFromDto(AlarmDto dto);public List<Alarm> getAlarm(Long target);
public List<Alarm> getAlarmGeneral(Long target);
public void deleteAlarm(Long id);

### AlarmAdminService : 
public AlarmDto getQueueAlarm()
public List<Alarm> getAlarm(String type)

## 레포지토리

private final AlarmRepository :
  List<Alarm> findByUserIdAndAlarmType(@Param("userId") Long userId, 

@Param("alarmType") AlarmType alarmType);
private final AlarmTargetRepository :

## 엔티티

### alarm : 
  Alarm
  AlarmTarget
  Subscription
