### ISSUE TITLE
[Feature] 회원가입 & 유저 관련 추가 기능 구현

### ISSUE THREAD

**Issue by sinryuji** [peer-42seoul/Peer-Backend#63]
### Description
회원가입과 유저에 관련해서 추가 필요한 기능들을 구현합니다

### To-Do
- [x] 이메일 중복 확인
- [x] 이메일로 코드 전송
- [x] 인증코드 검증
- [x] 닉네임 중복 확인
- [x] 유저 탈퇴
- [x] 어드민 권한
