### ISSUE TITLE
[REFACTOR] 테스트 서버 배포 dev로 옮기기

### ISSUE THREAD

**Issue by wochae** [peer-42seoul/Peer-Backend#643]
### Description
기존 test 브랜치가 아닌 dev에 파일을 배포하도록 수정.
### To-Do
- [x] Test_CICD 에 빌드 배포 확인
- [x] 테스트 서버 내 도커 이미지에 업로드 됐는지 확인
- [x] 자동으로 서버가 갱신되는지 확인
