### ISSUE TITLE
[FEAT] Calendar Data Sync Feature

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/Peer-Backend#744]
### Description
- 캘린더 위젯 기능 구현시 사용자 사용성을 제고하고자, 위젯 생성 시 기존의 기록들과 동기화 될 수 있도록 만들어줘야 한다. 

### To-Do
- [ ] 최초 동기화 하는 api 필요 
- [ ] 기존 알림을 등록해주는 api들을 개선하여 캘린더 등록이 가능하도록 내부 구조 리펙토링
- [ ] 알림을 기록할 테이블 생성 및 레포지터리 준비
